<a href="https://colab.research.google.com/github/MarckRosas1/ejercicioModulo1/blob/master/Python_B%C3%A1sico_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1: Arreglos**

### Importación de la librería

In [1]:
import numpy as np

### Creación de arreglo con función array

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

### Cantidad de datos almacenados en el array



In [6]:
a.size

5

### Cantidad de dimensiones del array




In [7]:
a.ndim

1

### Tipo de datos contenidos en el array

In [8]:
a.dtype

dtype('int64')

### Dimensiones del array

In [9]:
a.shape

(5,)

### Asignación de un arreglo a la variable a. La longitud del array es fija una vez que se define.

In [10]:
a=np.array([1,2,3,4,5])

## **2: Operaciones**

In [11]:
a=np.array([1,2,3,4,5])

### Suma

In [12]:
a+10

array([11, 12, 13, 14, 15])

### Resta

In [13]:
a-10

array([-9, -8, -7, -6, -5])

### Multiplicación

In [14]:
a*10


array([10, 20, 30, 40, 50])

### División

In [15]:
a/10

array([0.1, 0.2, 0.3, 0.4, 0.5])

### ***El array original no se modifica***





In [16]:
a

array([1, 2, 3, 4, 5])

### Operaciones con dos arrays

In [17]:
b=np.array([6,7,8,9,10])

### Suma de dos arrays

In [18]:
a+b

array([ 7,  9, 11, 13, 15])

### Multiplicación de dos arrays

In [19]:
a*b

array([ 6, 14, 24, 36, 50])

### División de dos arrays

In [20]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

### Resta de dos arrays

In [21]:
a-b

array([-5, -5, -5, -5, -5])

### El array original almacenado en la variable a se sigue manteniendo

In [22]:
a

array([1, 2, 3, 4, 5])

## 3: Tipos de datos

In [23]:
a= np.array([1,2,3,4,5])

In [24]:
a

array([1, 2, 3, 4, 5])

### Tipo de dato

In [25]:
a.dtype

dtype('int64')

### Se puede definir el tipo de dato que puede almacenar el array con dtype. En este caso de tipo float.

In [26]:
a=np.array([1,2,3,4,5], dtype=float)

In [27]:
a

array([1., 2., 3., 4., 5.])

### Array de tipo string.

In [28]:
a=np.array([1,2,3,4,5], dtype=str)

In [29]:
a

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Array de tipo boleano.

In [30]:
a=np.array([1,2,3,4,5], dtype=bool)

In [31]:
a

array([ True,  True,  True,  True,  True])

In [32]:
a=np.array([0,1,2,3,4,5], dtype=bool)

In [33]:
a

array([False,  True,  True,  True,  True,  True])

### Array de tipo números complejos.

In [34]:
a=np.array([0,1,2,3,4,5], dtype=np.complex)

<ipython-input-34-1c81aab052c4>:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.array([0,1,2,3,4,5], dtype=np.complex)


In [35]:
a

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

## **4: Crear arreglos (arrays)**





In [36]:
np.array([True, True, False])

array([ True,  True, False])

### **Función arrange**

In [37]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [38]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### **Arreglo del 0 al 20 con salto de 2 en 2**





In [39]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### **Arreglos de ceros**

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
np.zeros(10, dtype=int).dtype

dtype('int64')

### **Arreglos de unos**

In [43]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### **Arreglos con datos basura**

In [44]:
np.empty(10)

array([4.83993517e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.57903575e-310, 1.25740230e-071, 2.10654099e-052, 7.73783904e-091,
       2.32013919e-056, 6.57907572e-310])

In [45]:
np.empty(10, dtype=int)

array([     97961378340950,                   0,                   0,
                         0,     133161166045184, 3546082660938168372,
       3833738906545238061, 3258697620212507443, 3774637052015096628,
           133161974969911])

### **Arreglo con datos aleatorios**

Función random.randint(valor inicial, valor final, cantidad de números aleatorios)

In [46]:
np.random.randint(0,100,50)

array([30, 28, 72, 10, 86, 55, 49,  2, 36,  5, 43, 56, 72, 24, 91, 78, 74,
       20, 38, 88,  0, 88, 31, 99, 33, 31, 99, 62, 68, 53, 49, 32, 34, 48,
       26, 36, 29, 12,  7, 61, 28, 21, 77,  9, 77,  4, 22, 31, 36, 45])

## **5: Obtener y actualizar elementos**

In [47]:
import numpy as np

In [48]:
a=np.random.randint(0,10,10)

In [49]:
a

array([9, 5, 0, 4, 3, 3, 1, 8, 0, 0])

### Obtener un elemento del arreglo

In [50]:
a[0]

9

In [51]:
a[1]

5

In [52]:
a[2]

0

Cuando se colocan números negativos para obtener un elemento, se hace el recorrido del array de derecha a izquierda.

In [53]:
a[-1]

0

In [54]:
a[-2]

0

In [55]:
a[-3]

8

### Reemplazar un el valor de un elemento en un array

In [56]:
a

array([9, 5, 0, 4, 3, 3, 1, 8, 0, 0])

In [57]:
a[0]=500

In [58]:
a

array([500,   5,   0,   4,   3,   3,   1,   8,   0,   0])

## **6: Subarreglos**

In [59]:
a=np.random.randint(0,10,20)
a

array([9, 5, 7, 6, 6, 7, 6, 6, 6, 2, 4, 9, 0, 9, 9, 9, 6, 4, 5, 6])

In [60]:
# a[start:end:saltos]

In [61]:
a[0:5]

array([9, 5, 7, 6, 6])

In [62]:
a[:5]

array([9, 5, 7, 6, 6])

In [63]:
a[5:]

array([7, 6, 6, 6, 2, 4, 9, 0, 9, 9, 9, 6, 4, 5, 6])

In [64]:
a[5::2]

array([7, 6, 2, 9, 9, 9, 4, 6])